"""empty message

Revision ID: 4a784305b5d7
Revises: ea4195b1c17f
Create Date: 2021-05-13 16:39:12.089649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a784305b5d7'
down_revision = 'ea4195b1c17f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comment_ticket_id_fkey', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'ticket', ['ticket_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key('comment_ticket_id_fkey', 'comment', 'ticket', ['ticket_id'], ['id'])
    # ### end Alembic commands ###
